In [3]:
import numpy as np
import torch

In [5]:
arr2 = np.array([1,2,3,4])
print(arr2)
print(type(arr2))

[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
tens2=torch.from_numpy(arr2)
print(tens2)
print(type(tens2))

tensor([1, 2, 3, 4])
<class 'torch.Tensor'>


In [8]:
tens2[1]=10
print(tens2)

tensor([ 1, 10,  3,  4])


In [10]:
print(arr2)

[ 1 10  3  4]


In [11]:
arr3 = np.array([10,11,12,13])
tens3= torch.tensor(arr3)
print(tens3)
print(type(tens3))

tensor([10, 11, 12, 13])
<class 'torch.Tensor'>


In [12]:
tens3[0]=14
print(tens3)
print(arr3)

tensor([14, 11, 12, 13])
[10 11 12 13]
